### ISSUE TITLE
Images in main page are not displayed

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#1]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/f081127b-0877-49bf-941a-7da59311efae)

**Comment by Japoivvb** [comment]
evidence must be attached to close the issue

**Comment by arileccese** [comment]
[Evidencias Images JSP Arianna Leccese.pdf](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/files/15324608/Evidencias.Images.JSP.Arianna.Leccese.pdf)

**Comment by arileccese** [comment]
Hecho.

**Comment by Japoivvb** [comment]
then move it to "in review" column as request in steps please

**Comment by arileccese** [comment]
> then move it to "in review" column as request in steps please

Done

**Comment by Japoivvb** [comment]
well, next time as screenshot attached instead a file to avoid an extra step(download)
