### ISSUE TITLE
Update product image with best quality, it is pixeled now

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#10]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/a8014f86-2a8d-4699-a13f-f0ae9052b9f0)

**Comment by Abel1002** [comment]
<img width="959" alt="image" src="https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/147430925/03648199-244a-47b6-91bc-b3106d79eeb0">

**Comment by Japoivvb** [comment]
good job, but you must merge your code from your branch to master. please folllow instructions steps 7
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/96ac2d1c-24ec-425e-ae5b-d794aa478805)

**Comment by Japoivvb** [comment]
well done, but please do not forget the methodology, after that move it to "in review" status/column to be able to close it
