### ISSUE TITLE
Fix category product name, the current value is not right

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#11]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/d520b658-7ccb-4ffb-9fc4-35d6786da52d)

**Comment by Japoivvb** [comment]
evidence must be attached to close the issue

**Comment by user220205** [comment]
![Image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/146854636/1b87277f-1188-43ed-971c-1d4a7c76b497)

**Comment by Japoivvb** [comment]
issue must be closed by who opens it, keep on mind next time
