### ISSUE TITLE
Include link from login to register form

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#13]
Add under login button a hyperlink to redirect to register.jsp
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/31e6c5f4-0c3c-411e-a3d3-1318b366c3f2)

**Comment by Jirsaao** [comment]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/145552020/b7852352-79c3-4e15-81af-ca1faca8d117)

**Comment by Japoivvb** [comment]
fine, closed, next time moved to in review column
