### ISSUE TITLE
icon login must be appear only when user is logged not before

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#14]
as is
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/8bbaf848-d4e3-49b5-a6ce-b907baed75e5)
to be
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/05e40aa5-6e85-463f-950b-e91abad98508)
once logged in web, beside logout
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/d7a8275b-6067-4d35-a97c-9f236f039345)

**Comment by SergiGuasp** [comment]
![Image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/135022749/1a41e1eb-6e76-449a-8b2c-ddddf1c873ce)
![Image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/135022749/759bc86c-de23-4a81-b8a5-0f3ec724a6e9)

**Comment by Japoivvb** [comment]
I think it is pending pull request + merge from your branch to main, if not the change cannot be deployed

**Comment by Japoivvb** [comment]
and do not forget move it to in review column  then

**Comment by Japoivvb** [comment]
good job, review all steps that you did, the methodology is important to no forget any step
