### ISSUE TITLE
change error message when an item is already in the cart

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#15]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/65ee2e1c-96f6-44b1-9ed7-dacaf0ccde85)
change to "Sorry, the item that you selected is already in your cart. Go to Cart Page"

**Comment by Samixanxo** [comment]
<img width="956" alt="image" src="https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/114580765/dd8b0214-e38a-4471-90d6-053cf52c71c8">

**Comment by Japoivvb** [comment]
working fine, closed
