### ISSUE TITLE
add new product to shop

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#16]
Description: Men stylish elegant shoes 908
Price: 52
Category: Men Shoes
Photo
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/049a9f94-9dc8-4ca0-9665-b2c53140f437)

**Comment by Oscarg4** [comment]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/146353899/a5a59dba-e2c0-4e8c-b434-4e887175c2be)

**Comment by Oscarg4** [comment]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/146353899/37badd38-5cfc-4c26-a2ae-f95b4698a10f)

**Comment by Oscarg4** [comment]
This is the correction.

**Comment by Japoivvb** [comment]
the change was not merged to master, please review every step in instruction, the step 7 is missed
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/edad8270-52f9-45a2-8350-0907d7aa0f95)

**Comment by Japoivvb** [comment]
verified, thanks

**Comment by Japoivvb** [comment]
in merge action, some previous changes were missed, you must do pull before any change to avoid it
