### ISSUE TITLE
Error when click on Checkout if card is empty or login is not done, disable button or capture exception to show no products are selected

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#2]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/7905dc25-4dc2-440a-b09f-983d00e41cf6)
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/064dec58-98fc-4c15-b02a-9b00c4557760)

**Comment by Japoivvb** [comment]
evidence it is working must  be attached to close it

**Comment by gordo1998** [comment]
Without user and Cart:


![Image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/133088258/3ff5458c-1321-4f7d-82d0-6af9dfcfa86e)

Page Cart:



![Image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/133088258/19d05778-8f7d-4e37-811d-857ba9297d00)


With user and Cart:



![Image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/133088258/a1fcccdb-1e1f-49d7-bd95-f0346ecd0a82)

Page Cart:



![Image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/133088258/bee1d71c-5156-4711-b9d6-3d20d6bae64b)

Code Cart.jsp:



![Image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/133088258/0f8e86a4-ca32-47ab-bbd4-af5322aabdb2)

**Comment by Japoivvb** [comment]
good job, but next time if the whole application is in English, keep the language in all parts, escpecially in messages to the user.
