### ISSUE TITLE
Show currency ($) in order list beside the price for each product

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#21]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/eaac8e9f-44b1-49fb-91e8-6032ad3af7c6)

**Comment by IIH10** [comment]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/137720468/8688ff85-aa06-4003-a8d5-ea25414c0679)

**Comment by IIH10** [comment]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/137720468/b2f4183f-409f-492e-8c25-c50fc7657fc9)

**Comment by IIH10** [comment]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/137720468/d9ece285-376e-40c6-9e1c-290806d74eb1)

**Comment by Japoivvb** [comment]
well done, it sould be better at left from price as other similar prices do, do not change, it will do in future for other programmer.
