### ISSUE TITLE
Change column title in card list from Buy Now to Quantity

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#23]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/c6a17449-b74b-459e-8169-469ea6cf1cdf)

**Comment by Ayesta1** [comment]
Por problemas con el MAC le he pedido ayuda a Pol para poder hacer el commit push des de su ordenador por eso sale su nombre.
Aqui abajo adjunto la foto del resultado
![Captura de pantalla 2024-05-13 a las 19 20 24](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/147074670/17c95a2b-41e5-428e-b0fe-8ba10ed5b5fc)

**Comment by Japoivvb** [comment]
evidence must be attached to close the issue

**Comment by Japoivvb** [comment]
none evidence is still attached

**Comment by Japoivvb** [comment]
none evidence, it cannot be evaluated to close

**Comment by Ayesta1** [comment]
![Captura de pantalla 2024-05-21 a las 15 29 22](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/147074670/03426d29-500d-4a27-b434-cb1529ee00c4)
