### ISSUE TITLE
Show message in orders view after click on Home/buy now or cart/buy

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#24]
in order to clarify the order was done, show a message to the client
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/c5362c2e-3786-4c2a-98eb-90ecb88ddb39)

**Comment by Japoivvb** [comment]
code is not rigth, the message must be showed in cart view instead orders view, this has to be done from beginning
1. remove current user branch
2. create a new one
3. do the proper change
4. so on

**Comment by RovisRon** [comment]
![Captura de pantalla 2024-06-13 a las 15 42 26](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/57545181/3cd9dbc6-6cba-41fa-9bb2-3f6b5437d5c0)

**Comment by Japoivvb** [comment]
the message was requested to be showed above orders list not below, the rest is ok, enough to close the issue
