### ISSUE TITLE
Change cart product counter from red to green

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#25]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/e27b25c1-f28a-4394-ac46-248afb13b8f9)

**Comment by Adriaris** [comment]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/124537287/c112be4f-8bf3-4df5-baaf-d32f2463ebab)

Como usa bootstrap, cambio el badge-danger por el badge-success

![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/124537287/823ee00e-7e40-4e52-941d-ec7d82450256)
