### ISSUE TITLE
Show 2 decimals in price even they are 0s

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#4]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/6f5c3737-c6bf-4041-add8-f4a44bc55d3a)

**Comment by Japoivvb** [comment]
none evidence attached and commit was not done properly
so change cannot be verified and therefore merge to master is not possible. You have to do two thing to be able promote the fix.

**Comment by Kalaka07** [comment]
El issue no está comentado como #4? Allí subí todo mi código.

**Comment by Japoivvb** [comment]
Hola Aarón,
el problema no es del commit message que si tiene la referencia, el
problema es que has subido el código como un fichero por Google Drive con
lo que sobre escribirías todo el código, se ha de subir usando comandos git
y solo con los cambios relativos a tu cambio. Comentamos martes en proyecto.

**Comment by Japoivvb** [comment]
it has to be done from beginning
1. remove current user branch
2. create a new branch
3. do commit properly
4. so on

**Comment by Kalaka07** [comment]
![Captura de pantalla 2024-05-17 231837](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/86265629/2209dcd0-fb1c-4a6f-8403-ee8267cb075c)

**Comment by Japoivvb** [comment]
everything is working
