### ISSUE TITLE
add new product to shop

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#47]
Description: Saint Laurent Desk Agenda In Leather
Price: 13
Category: Men Agenda
Photo
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/f90df67f-741d-4b95-9c7d-8d6b25c7dae2)

**Comment by Kalaka07** [comment]
He añadido un nuevo producto a la base de datos y añadido la imagen de este al proyecto.

![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/86265629/787dc1e0-c16c-435d-a874-c4afa2fd9b10)

**Comment by Japoivvb** [comment]
done as requested
