### ISSUE TITLE
Fix error typo in model.Order

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#5]
https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/blob/11e8fcd7ff1ec99c413ae79de12b35601cdde679/src/main/java/val/shop/model/Order.java#L6
change attribute name to correct "quantity"

**Comment by dinanli2002** [comment]
<img width="734" alt="Screenshot 2024-05-14 at 18 47 07" src="https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/135025231/9d83f809-490b-41b8-bfa4-c4bdc5068b7f">
<img width="559" alt="Screenshot 2024-05-14 at 18 47 26" src="https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/135025231/0fd0d597-9f67-48bf-8058-f069419027bd">
<img width="461" alt="Screenshot 2024-05-14 at 18 47 38" src="https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/135025231/3ed76f79-e058-4b71-a668-88051891759f">
<img width="826" alt="Screenshot 2024-05-14 at 18 48 39" src="https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/135025231/e7716dbd-ea5a-4591-ab4a-2dcac66955c3">

**Comment by Japoivvb** [comment]
check if the change was moved from your branch to main with pull request + merge. Step 7. Push to your branch, pull request to main, resolve conflicts in case there are

**Comment by dinanli2002** [comment]
<img width="734" alt="Screenshot 2024-05-14 at 18 47 07" src="https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/135025231/b858537f-f2d2-4479-a58c-0c4397fd0059">
<img width="734" alt="Screenshot 2024-05-14 at 18 47 07" src="https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/135025231/b858537f-f2d2-4479-a58c-0c4397fd0059">
<img width="1109" alt="Screenshot 2024-05-16 at 17 53 45" src="https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/135025231/94f9800d-e2fa-4cf5-8030-35020cb77768">
<img width="1109" alt="Screenshot 2024-05-16 at 17 53 45" src="https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/135025231/94f9800d-e2fa-4cf5-8030-35020cb77768">

**Comment by Japoivvb** [comment]
good job, but please remove your credentials from connection SQL database
