### ISSUE TITLE
Change title from "Shopping Cart" to "Shopping Stufy" and include a proper icon

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#6]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/38ac2d46-4a22-4e77-ac25-0b26bb858382)

**Comment by larawrd** [comment]
#6

![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/160758773/81ec0541-09ac-4ffc-938e-6d7b87941ec2)
He agregado un icono y he actualizado el nombre
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/160758773/7ac4f552-ed87-4ef3-8a97-6b6630a01234)
Dentro de navbar.jsp es donde está el html de el encabezaso, ahí he cambiado el nombre y he añadido una imagen que es el icono.
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/160758773/7aa12c18-880a-42a7-aaa6-4ba7aca59bb2)
Aqui se puede ver que he agregado la imagen del icono llamada "shein.png"

**Comment by Japoivvb** [comment]
everything was done as expected
