### ISSUE TITLE
Show total cost of orders under the current Orders list, as sum of every price order

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#8]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/1095b609-7710-4751-8c95-9ce0a9d6b9f7)

**Comment by arnial10** [comment]
![Image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/133888394/bd3b7cc6-c64e-44d8-b8f1-88bd561ad6bc)

**Comment by Japoivvb** [comment]
good job, but it is clear the precision  must be trim to 2 decimals as rest of application, do not change, it will be done in future for other programmer
