### ISSUE TITLE
include footer page in error page when login is not ok

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAM2_M06_UF4_JSP_eShop#9]
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/88535aab-a1e3-44b0-9cc9-f24e227c5898)
add web footer
![image](https://github.com/Stucom-Pelai/DAM2_M06_UF4_JSP_eShop/assets/36648472/710265d1-dd18-414f-9328-8c5c512c7d07)

**Comment by FranS111** [comment]
Dev:
- Affected Components: error.jsp, footer.jsp, login.jsp, LoginServlet.java
- Description: 
 -error.jsp: Include the &lt;jsp:include&gt; tag to incorporate the footer.jsp at the bottom of the error page.Change: Add &lt;jsp:include 
  page="footer.jsp"/&gt; before the closing &lt;/body&gt; tag.
 -footer.jsp: Ensure that the footer content is correctly defined and styled to be included in other JSP pages.Change: Verify and update the 
  content and styling as necessary to be compatible with the error page.
 -login.jsp: Ensure redirection to error.jsp when login fails.Change: Check that the LoginServlet.java redirects to error.jsp on login failure.
 -LoginServlet.java: Modify the servlet to redirect to error.jsp with appropriate error messages.Change: Update the doPost method to 
  forward to error.jsp if the login credentials are incorrect.

Test:
-Setup: Ensure that the footer.jsp is correctly styled and accessible.
-Login with Incorrect Credentials: Go to the login page (login.jsp). Enter invalid username and password. Submit the form.
-Verify Error Page: Check that the error page (error.jsp) is displayed. Ensure the footer is visible at the bottom of the error page, with correct styling and content.
-User Experience: Verify that the error message is clear and the footer is correctly included, enhancing the user experience.

**Comment by Japoivvb** [comment]
everything done as requested
